"""The alembic chain equals the models (DESIGN §5.3, §7.3 ``tests/unit/test_migrations_match_metadata.py``):
``alembic upgrade head`` on a temp SQLite file produces a schema whose autogenerate diff against
``Base.metadata`` is empty, carries exactly the triggers ``create_schema`` installs, downgrades
cleanly, and the revision file freezes the wall markers and the per-role grants without importing
the models. The offline (``--sql``) script is Postgres-only and carries the roles, grants, RLS
policies and partial indexes.
"""

from __future__ import annotations

import ast
import importlib.util
import os
from pathlib import Path
from types import ModuleType
from typing import Any

import pytest
from alembic import command
from alembic.autogenerate import compare_metadata
from alembic.config import Config
from alembic.runtime.migration import MigrationContext
from alembic.script import ScriptDirectory
from alembic.util.exc import AutogenerateDiffsDetected, CommandError
from sqlalchemy import inspect
from sqlalchemy.engine import Engine

from nour.db.base import Base
from nour.db.engine import (
    GRANTS_KEY,
    create_schema,
    install_sqlite_schema_translation,
    make_engine,
    table_flags,
)
from nour.db.models import metadata_for_dialect

REPO = Path(__file__).resolve().parents[2]
MIGRATIONS = REPO / "nour" / "db" / "migrations"
REVISION_FILE = MIGRATIONS / "versions" / "0001_initial.py"

SQLITE_TRIGGERS = 67
"""8 append-only tables x 3, 20 single-transition columns, 8 kept-rows tables x 2, 6 immutable
tables x 1, 1 forward-only column (``tests/unit/test_single_transition.py`` counts the same)."""

PARTIAL_INDEXES = (
    "CREATE INDEX ix_approval_decision ON approval (decision) WHERE decision IS NULL",
    "CREATE INDEX ix_freeze_state_released_at ON freeze_state (released_at) "
    "WHERE released_at IS NULL",
    "CREATE INDEX ix_pending_owner_message_sent_at ON pending_owner_message (sent_at) "
    "WHERE sent_at IS NULL",
)


def _config(url: str) -> Config:
    cfg = Config()
    cfg.set_main_option("script_location", str(MIGRATIONS))
    cfg.set_main_option("sqlalchemy.url", url)
    cfg.attributes["configure_logging"] = False
    return cfg


def _sqlite_url(tmp_path: Path, name: str) -> str:
    return f"sqlite+pysqlite:///{tmp_path / name}"


def _schema_objects(engine: Engine) -> dict[str, set[tuple[str, str]]]:
    """``{type: {(name, sql)}}`` from ``sqlite_master`` (tables, indexes, triggers)."""
    out: dict[str, set[tuple[str, str]]] = {"table": set(), "index": set(), "trigger": set()}
    with engine.connect() as connection:
        rows = connection.exec_driver_sql(
            "SELECT type, name, sql FROM sqlite_master WHERE sql IS NOT NULL"
        ).all()
    for type_, name, sql in rows:
        if name == "alembic_version" or name.startswith("sqlite_"):
            continue
        out[type_].add((name, _normalise(sql)))
    return out


def _normalise(sql: str) -> str:
    """One-line SQL with the top-level clauses of a CREATE TABLE body sorted: alembic's
    ``op.create_table`` and ``create_all`` order the constraints differently and nothing else."""
    flat = " ".join(sql.split())
    if not flat.upper().startswith("CREATE TABLE"):
        return flat
    head, _, rest = flat.partition("(")
    body = rest.rsplit(")", 1)[0]
    clauses: list[str] = []
    depth = 0
    current = ""
    for char in body:
        if char == "(":
            depth += 1
        elif char == ")":
            depth -= 1
        if char == "," and depth == 0:
            clauses.append(current.strip())
            current = ""
        else:
            current += char
    clauses.append(current.strip())
    return head.strip() + " (" + ", ".join(sorted(clauses)) + ")"


def _load_revision() -> ModuleType:
    spec = importlib.util.spec_from_file_location("nour_db_revision_0001", REVISION_FILE)
    assert spec is not None and spec.loader is not None
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


# --------------------------------------------------------------------------- configuration


def test_alembic_ini_points_at_the_migrations_and_one_revision() -> None:
    cfg = Config(str(REPO / "alembic.ini"))
    cfg.attributes["configure_logging"] = False
    script = ScriptDirectory.from_config(cfg)
    assert Path(script.dir).resolve() == MIGRATIONS.resolve()
    assert script.get_heads() == ["0001"]
    head = script.get_revision("0001")
    assert head is not None and head.down_revision is None
    assert (MIGRATIONS / "env.py").is_file() and (MIGRATIONS / "script.py.mako").is_file()
    assert not cfg.get_main_option("sqlalchemy.url")  # URLs come from the env, never the ini


def test_revision_freezes_the_markers_and_grants_without_importing_the_models() -> None:
    tree = ast.parse(REVISION_FILE.read_text(encoding="utf-8"))
    imported: set[str] = set()
    for node in ast.walk(tree):
        if isinstance(node, ast.Import):
            imported.update(alias.name for alias in node.names)
        elif isinstance(node, ast.ImportFrom) and node.module:
            imported.add(node.module)
            imported.update(f"{node.module}.{alias.name}" for alias in node.names)
    assert not any(name.startswith("nour.db.models") for name in imported), imported
    assert {"nour.db.engine.trigger_ddl", "nour.db.engine.pg_roles_ddl"} <= imported
    revision = _load_revision()
    assert revision.revision == "0001" and revision.down_revision is None
    expected_flags = {
        table.key: {
            "scope": table_flags(table)["scope"].value,
            "append_only": table_flags(table)["append_only"],
            "single_transition": tuple(table_flags(table)["single_transition"]),
            "forward_only": {k: list(v) for k, v in table_flags(table)["forward_only"].items()},
            "immutable": tuple(table_flags(table)["immutable"]),
            "desk_partitioned": table_flags(table)["desk_partitioned"],
        }
        for table in Base.metadata.sorted_tables
    }
    assert revision.TABLE_FLAGS == expected_flags
    expected_grants = {
        table.key: {role: dict(grant) for role, grant in table.info[GRANTS_KEY].items()}
        for table in Base.metadata.sorted_tables
        if table.info.get(GRANTS_KEY)
    }
    assert revision.GRANTS == expected_grants
    assert set(expected_grants) == {
        "inbox_event",
        "handoff",
        "approval",
        "release",
        "passphrase_attempt",
        "dnc_entry",
        "freeze_state",
        "coat",
    }


# --------------------------------------------------------------------------- the chain on SQLite


def test_upgrade_head_yields_an_empty_autogenerate_diff(tmp_path: Path) -> None:
    url = _sqlite_url(tmp_path, "migrated.sqlite3")
    command.upgrade(_config(url), "head")
    engine = make_engine(url)
    try:
        install_sqlite_schema_translation(engine, Base.metadata)
        with engine.connect() as connection:
            context = MigrationContext.configure(
                connection,
                opts={
                    "compare_type": True,
                    "compare_server_default": True,
                    "include_schemas": False,
                },
            )
            assert context.get_current_revision() == "0001"
            diff = compare_metadata(context, metadata_for_dialect("sqlite"))
        assert diff == [], diff
        tables = set(inspect(engine).get_table_names())
        assert tables == {t.name for t in Base.metadata.sorted_tables} | {"alembic_version"}
    finally:
        engine.dispose()


def test_alembic_check_passes_through_the_projects_own_env(tmp_path: Path) -> None:
    """``uv run alembic check`` is what the lead runs: env.py's own comparison must be clean."""
    url = _sqlite_url(tmp_path, "checked.sqlite3")
    cfg = _config(url)
    command.upgrade(cfg, "head")
    command.check(cfg)  # raises AutogenerateDiffsDetected on any drift
    engine = make_engine(url)
    try:
        with engine.begin() as connection:  # drift the database: the check must notice
            connection.exec_driver_sql("CREATE TABLE stray (x INTEGER)")
    finally:
        engine.dispose()
    with pytest.raises(AutogenerateDiffsDetected, match="stray"):
        command.check(cfg)


def test_migration_and_create_schema_produce_the_same_sqlite_schema(
    tmp_path: Path,
) -> None:
    migrated_url = _sqlite_url(tmp_path, "migrated.sqlite3")
    command.upgrade(_config(migrated_url), "head")
    migrated = make_engine(migrated_url)
    created = make_engine(_sqlite_url(tmp_path, "created.sqlite3"))
    try:
        create_schema(created, Base.metadata)
        a, b = _schema_objects(migrated), _schema_objects(created)
    finally:
        migrated.dispose()
        created.dispose()
    assert {name for name, _ in a["table"]} == {name for name, _ in b["table"]}
    assert a["trigger"] == b["trigger"]  # same statements from the same generators
    assert a["index"] == b["index"]
    assert a["table"] == b["table"]
    assert len(a["trigger"]) == SQLITE_TRIGGERS
    names = {name for name, _ in a["trigger"]}
    assert {"release_no_delete", "release_no_replace", "release_immutable"} <= names
    assert {"approval_immutable", "inbox_event_immutable", "document_immutable"} <= names
    signature = next(sql for name, sql in a["table"] if name == "inbox_event")
    assert "signature_valid BOOLEAN DEFAULT 0 NOT NULL" in signature  # the one server default


def test_downgrade_to_base_drops_every_table(tmp_path: Path) -> None:
    url = _sqlite_url(tmp_path, "down.sqlite3")
    cfg = _config(url)
    command.upgrade(cfg, "head")
    command.downgrade(cfg, "base")
    engine = make_engine(url)
    try:
        assert set(inspect(engine).get_table_names()) <= {"alembic_version"}
        with engine.connect() as connection:
            triggers = connection.exec_driver_sql(
                "SELECT count(*) FROM sqlite_master WHERE type = 'trigger'"
            ).scalar()
        assert triggers == 0
        command.upgrade(cfg, "head")  # and the chain is re-runnable
        assert len(inspect(engine).get_table_names()) == 35
    finally:
        engine.dispose()


# --------------------------------------------------------------------------- offline SQL


def test_offline_sql_mentions_triggers_roles_grants_policies_and_partial_indexes(
    capsys: Any,
) -> None:
    command.upgrade(_config("postgresql+psycopg://nour:nour@localhost/nour"), "head", sql=True)
    sql = capsys.readouterr().out
    assert 'CREATE SCHEMA IF NOT EXISTS "auditor"' in sql
    assert (
        'CREATE TABLE "auditor"."auditor_report"' in sql
        or "CREATE TABLE auditor.auditor_report" in sql
    )
    assert "nour_refuse_append_only" in sql and "RAISE EXCEPTION" in sql
    assert "nour_refuse_delete" in sql and 'CREATE TRIGGER "release_no_delete"' in sql
    assert "nour_immutable_approval" in sql and 'CREATE TRIGGER "approval_immutable"' in sql
    assert 'CREATE ROLE "nour_desk_operator" NOLOGIN' in sql
    assert "FORCE ROW LEVEL SECURITY" in sql and "CASE current_user" in sql
    assert "current_setting(" not in sql
    # per-role grants
    assert (
        'GRANT UPDATE ("acked_at", "parked_until", "lock_until", "error") ON "inbox_event"' in sql
    )
    assert 'REVOKE INSERT, UPDATE, DELETE ON "inbox_event" FROM "nour_desk_operator"' in sql
    assert 'GRANT INSERT ("id", "created_at", "updated_at", "desk"' in sql
    assert 'GRANT DELETE ON "inbox_event" TO "nour_scheduler"' in sql
    assert 'REVOKE INSERT, UPDATE, DELETE ON "handoff" FROM "nour_desk_operator"' in sql
    assert 'GRANT UPDATE ("taken_at") ON "handoff" TO "nour_desk_operator"' in sql
    assert 'GRANT INSERT ON "handoff" TO "nour_desk_assistant"' in sql
    assert 'GRANT UPDATE ("burnt_at") ON "release" TO "nour_desk_operator"' in sql
    # the desk partition of inbox_event
    assert 'ALTER TABLE "inbox_event" FORCE ROW LEVEL SECURITY' in sql
    assert 'CREATE POLICY "inbox_event_desk_partition_read" ON "inbox_event" FOR SELECT' in sql
    assert 'CREATE POLICY "inbox_event_desk_partition_insert" ON "inbox_event" FOR INSERT' in sql
    # partial indexes (alembic's Postgres compare ignores postgresql_where, so the text is checked)
    for statement in PARTIAL_INDEXES:
        assert statement in sql, statement
    assert "signature_valid BOOLEAN DEFAULT false NOT NULL" in sql


def test_offline_sql_is_refused_for_sqlite(tmp_path: Path) -> None:
    """Offline SQL would carry schema-qualified DDL SQLite cannot run (env.py docstring)."""
    with pytest.raises(CommandError, match="Postgres-only"):
        command.upgrade(_config(_sqlite_url(tmp_path, "offline.sqlite3")), "head", sql=True)


# --------------------------------------------------------------------------- postgres

PG_URL = os.environ.get("NOUR_DATABASE_URL", "")


@pytest.mark.postgres
@pytest.mark.skipif(not PG_URL.startswith("postgresql"), reason="NOUR_DATABASE_URL is not Postgres")
def test_postgres_upgrade_head_yields_an_empty_diff_with_schemas() -> None:
    engine = make_engine(PG_URL)
    try:
        Base.metadata.drop_all(engine)
        with engine.begin() as connection:
            connection.exec_driver_sql("DROP TABLE IF EXISTS alembic_version")
        command.upgrade(_config(PG_URL), "head")
        with engine.connect() as connection:
            context = MigrationContext.configure(
                connection,
                opts={
                    "compare_type": True,
                    "compare_server_default": True,
                    "include_schemas": True,
                },
            )
            diff = compare_metadata(context, metadata_for_dialect("postgresql"))
            # alembic does not compare postgresql_where: prove the predicates were created
            indexdefs: dict[str, str] = {
                name: definition
                for name, definition in connection.exec_driver_sql(
                    "SELECT indexname, indexdef FROM pg_indexes WHERE indexname IN "
                    "('ix_approval_decision', 'ix_freeze_state_released_at', "
                    "'ix_pending_owner_message_sent_at')"
                ).all()
            }
        assert diff == [], diff
        assert set(indexdefs) == {
            "ix_approval_decision",
            "ix_freeze_state_released_at",
            "ix_pending_owner_message_sent_at",
        }
        assert all(
            "WHERE" in definition and "IS NULL" in definition for definition in indexdefs.values()
        )
    finally:
        engine.dispose()
